import { motion } from "framer-motion";
import { GraduationCap, Trophy, BookOpen } from "lucide-react";

const coursework = ["Machine Learning", "Deep Learning", "NLP", "Statistics", "Database Systems", "Data Structures", "Time Series", "SQL"];
const About = () => <section id="about" className="py-24 px-4 md:px-10 max-w-7xl mx-auto">
  <motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}>
    <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground mb-4">Background & Academics</p>
    <h2 className="text-3xl md:text-5xl font-bold leading-tight max-w-3xl">Finding useful answers in <span className="font-serif-italic text-accent">complex data</span></h2>
  </motion.div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-12">
    <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .5, delay: .2 }} className="space-y-6 flex flex-col justify-between">
      <div className="space-y-4"><p className="text-muted-foreground leading-relaxed">I'm <span className="text-foreground font-semibold">Arun Kethavath</span>, an IIT Kharagpur student pursuing an integrated B.Tech. (Hons.) and M.Tech. in Metallurgical and Materials Engineering, with a micro-specialization in Artificial Intelligence and Applications.</p><p className="text-muted-foreground leading-relaxed">My focus is data analytics and data science: querying and cleaning data, finding patterns, building clear dashboards, and evaluating statistical and machine-learning models.</p><p className="text-muted-foreground leading-relaxed">I have applied these skills to industrial sensor data, customer journeys, campaign performance, sales forecasts, and AI-assisted tools. I care about making the analysis understandable and useful to the people making decisions.</p></div>
      <div className="pt-4 border-t border-border"><h4 className="text-xs uppercase tracking-[0.2em] font-semibold flex items-center gap-2 mb-3"><BookOpen className="w-4 h-4 text-primary" /> Areas of study</h4><div className="flex flex-wrap gap-2">{coursework.map((item) => <span key={item} className="text-xs px-3 py-1 rounded-full bg-secondary/60 text-muted-foreground border border-border">{item}</span>)}</div></div>
    </motion.div>
    <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .5, delay: .3 }} className="space-y-6">
      <div className="bg-card rounded-2xl border border-border p-6 md:p-8"><h3 className="text-base font-semibold mb-6 flex items-center gap-2.5"><GraduationCap className="w-5 h-5 text-primary" /> Education</h3><div className="space-y-5"><div><p className="text-sm font-semibold">Indian Institute of Technology, Kharagpur</p><p className="text-xs text-muted-foreground mt-1">B.Tech. (Hons.) + M.Tech. · Metallurgical & Materials Engineering · 2022–2027</p><p className="text-xs text-muted-foreground mt-1">Micro-specialization in Artificial Intelligence and Applications · CGPA 8.2/10</p></div><div className="w-full h-px bg-border"/><div><p className="text-sm font-medium">Narayana Junior College</p><p className="text-xs text-muted-foreground mt-1">Class XII · TSBIE · 98.7% · 2022</p></div><div className="w-full h-px bg-border"/><div><p className="text-sm font-medium">Residential School</p><p className="text-xs text-muted-foreground mt-1">Class X · 2020</p></div></div></div>
      <div className="bg-card rounded-2xl border border-border p-6 md:p-8"><h3 className="text-base font-semibold mb-4 flex items-center gap-2.5"><Trophy className="w-5 h-5 text-primary" /> Leadership & community</h3><div className="space-y-4"><div><p className="text-sm font-semibold">General Secretary, Sports & Games · RP Hall</p><p className="text-xs text-muted-foreground mt-1 leading-relaxed">Led 15 secretaries and 17 captains across 25+ events, managing a ₹4.5M budget for 850+ residents.</p></div><div className="w-full h-px bg-border"/><div><p className="text-sm font-semibold">Publicity & Marketing · Shaurya</p><p className="text-xs text-muted-foreground mt-1 leading-relaxed">Led a 20-member team, creating 200+ posts and engaging 4,500+ students across 14+ events.</p></div></div></div>
    </motion.div>
  </div>
</section>;
export default About;
