import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, ChevronLeft, ChevronRight } from "lucide-react";

type Project = { title: string; description: string; tech: string[]; category: "Analytics & ML" | "Data Applications"; image: string; };
const projects: Project[] = [
  { title: "Agentic AI Personal Finance Assistant", description: "Designed a multi-agent assistant for real-time finance and web insights, using LLaMA 3.3, yFinance, and DuckDuckGo. Built modular research agents with source attribution and a FastAPI backend supporting 100+ concurrent requests at around 500 ms latency.", tech: ["LangChain", "LLaMA 3.3", "FastAPI", "yFinance"], category: "Analytics & ML", image: "/project-covers/finance-assistant.svg" },
  { title: "ClickAssist · Photography RAG Assistant", description: "Built a camera-manual assistant with section-aware retrieval and inline citations. Hybrid BGE and BM25 search improved retrieval accuracy from 70% to 80%, measured with a RAGAS evaluation harness.", tech: ["LangChain", "ChromaDB", "BM25", "RAGAS"], category: "Analytics & ML", image: "/project-covers/clickassist-rag.svg" },
  { title: "Sales Forecasting for LFS Channels", description: "Compared ARIMA, SARIMA, SARIMAX, LSTM, and GRU approaches, incorporating holidays and festivals into the analysis. Statistical testing and event-aware features helped reach 89% forecasting accuracy.", tech: ["Python", "SARIMAX", "Time Series", "Statistics"], category: "Analytics & ML", image: "/project-covers/sales-forecast.svg" },
  { title: "Lakeside · IIT Kharagpur Dating Platform", description: "Developed a recommendation model based on eight metrics, achieving a 74% satisfaction rate and 1,500+ sign-ups. Improved platform speed by 32% and used funnel analysis to identify opportunities to improve retention.", tech: ["Recommendations", "AWS EC2", "Azure Blob", "Hotjar"], category: "Data Applications", image: "/project-covers/lakeside-insights.svg" },
  { title: "SF Connect · Spring Fest App", description: "Helped build the official Android app for Spring Fest, adding telemetry heatmaps for 20,000+ users and supporting crowd-density forecasting across 100+ events. Integrated a PCI-compliant payment portal processing INR 70 lakh+ in transactions.", tech: ["Android", "Analytics", "Payments", "Product"], category: "Data Applications", image: "/project-covers/sf-connect-analytics.svg" },
  { title: "Medallion Data Warehouse & ETL", description: "Created a SQL Server warehouse with Bronze, Silver, and Gold layers for ERP and CRM data. Automated five ETL stages and modeled a star schema for analytics and BI tools.", tech: ["SQL Server", "ETL", "Data Modeling", "Power BI"], category: "Analytics & ML", image: "/project-covers/medallion-warehouse.svg" },
];
const ProjectCard = ({ project, index }: { project: Project; index: number }) => <motion.article initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .3, delay: index * .06 }} className="group bg-card rounded-2xl border border-border overflow-hidden hover:border-primary/50 transition-colors flex flex-col justify-between"><div><div className="aspect-video bg-secondary overflow-hidden"><img src={project.image} alt={`${project.title} cover illustration`} loading="lazy" className="w-full h-full object-cover grayscale transition-all duration-500 group-hover:grayscale-0 group-hover:scale-105" /></div><div className="p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.2em] text-primary mb-2">{project.category}</p><h3 className="text-xl md:text-2xl font-bold group-hover:text-primary transition-colors">{project.title}</h3></div><ArrowUpRight className="w-5 h-5 shrink-0 text-muted-foreground" /></div><p className="text-muted-foreground text-sm leading-relaxed mt-4">{project.description}</p></div></div><div className="px-6 pb-6 md:px-8 md:pb-8 flex flex-wrap gap-2">{project.tech.map((item) => <span key={item} className="text-[10px] uppercase tracking-widest px-2.5 py-1 rounded-full bg-secondary text-secondary-foreground border border-border">{item}</span>)}</div></motion.article>;

const ITEMS_PER_PAGE = 4;
const Projects = () => {
  const [filter, setFilter] = useState<"All" | "Analytics & ML" | "Data Applications">("All");
  const [page, setPage] = useState(0);
  const filtered = projects.filter((project) => filter === "All" || project.category === filter);
  const pages = Math.ceil(filtered.length / ITEMS_PER_PAGE);
  const shown = filtered.slice(page * ITEMS_PER_PAGE, (page + 1) * ITEMS_PER_PAGE);
  const changeFilter = (value: typeof filter) => { setFilter(value); setPage(0); };
  const changePage = (value: number) => {
    setPage(value);
    document.getElementById("projects")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return <section id="projects" className="py-24 px-4 md:px-10 max-w-7xl mx-auto"><motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .6 }} className="mb-16 flex flex-col md:flex-row md:items-end justify-between gap-8"><div><p className="text-xs uppercase tracking-[0.3em] text-muted-foreground mb-4">Data & applied AI</p><h2 className="font-display text-5xl md:text-7xl tracking-wider">ANALYTICAL <span className="font-serif-italic text-accent">Projects</span></h2></div><div className="flex flex-wrap bg-secondary/50 p-1 rounded-full border border-border self-start">{(["All", "Analytics & ML", "Data Applications"] as const).map((item) => <button key={item} onClick={() => changeFilter(item)} className={`px-5 py-2 rounded-full text-sm transition-all ${filter === item ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>{item}</button>)}</div></motion.div><AnimatePresence mode="wait"><motion.div key={`${filter}-${page}`} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} transition={{ duration: .25 }} className="grid grid-cols-1 md:grid-cols-2 gap-8">{shown.map((project, index) => <ProjectCard key={project.title} project={project} index={index} />)}</motion.div></AnimatePresence>{pages > 1 && <div className="mt-12 flex items-center justify-center gap-6"><button onClick={() => changePage(Math.max(page - 1, 0))} aria-label="Go to previous project page" disabled={page === 0} className="w-14 h-14 rounded-full border border-border flex items-center justify-center text-muted-foreground hover:text-foreground hover:border-primary/40 transition-all disabled:opacity-40 disabled:cursor-not-allowed"><ChevronLeft className="w-5 h-5" /></button><div className="flex items-center gap-3">{Array.from({ length: pages }, (_, index) => <button key={index} onClick={() => changePage(index)} aria-label={`Go to project page ${index + 1}`} className={`h-2 rounded-full transition-all ${page === index ? "bg-primary w-8" : "bg-border hover:bg-muted-foreground w-2"}`} />)}</div><button onClick={() => changePage(Math.min(page + 1, pages - 1))} aria-label="Go to next project page" disabled={page === pages - 1} className="w-14 h-14 rounded-full border border-border flex items-center justify-center text-muted-foreground hover:text-foreground hover:border-primary/40 transition-all disabled:opacity-40 disabled:cursor-not-allowed"><ChevronRight className="w-5 h-5" /></button></div>}</section>;
};
export default Projects;
